begin;

create table public.stocks (
    id bigint generated by default as identity primary key,

    product_id bigint not null unique
        references public.products(id)
        on delete cascade,

    min_stock integer not null default 0
        check (min_stock >= 0),
    stock_in integer not null default 0
        check (stock_in >= 0),
    stock_out integer not null default 0
        check (stock_out >= 0),
    stock_adjustment integer not null default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index stocks_product_id_idx
    on public.stocks(product_id);

alter table public.stocks enable row level security;

create policy "Public can read stocks"
    on public.stocks
    for select
    to public
    using (true);

create policy "Authenticated users can create stocks"
    on public.stocks
    for insert
    to authenticated
    with check (true);

create policy "Authenticated users can update stocks"
    on public.stocks
    for update
    to authenticated
    using (true)
    with check (true);

create policy "Authenticated users can delete stocks"
    on public.stocks
    for delete
    to authenticated
    using (true);

-- Backfill stock records for products that existed before this migration.
insert into public.stocks (product_id)
select id
from public.products
on conflict (product_id) do nothing;

create function public.create_stock_for_product()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.stocks (product_id)
    values (new.id)
    on conflict (product_id) do nothing;

    return new;
end;
$$;

create trigger create_stock_after_product_insert
after insert on public.products
for each row
execute function public.create_stock_for_product();

commit;
