begin;

create table public.picked_products (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    quantity integer not null check (quantity > 0),
    picked_by_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint picked_products_picker_product_unique unique (picked_by_id, product_id)
);

create index picked_products_product_id_idx on public.picked_products(product_id);
create index picked_products_picked_by_id_idx on public.picked_products(picked_by_id);

alter table public.picked_products enable row level security;

create policy "Authenticated users can read picked products"
    on public.picked_products for select to authenticated using (true);
create policy "Authenticated users can create their picked products"
    on public.picked_products for insert to authenticated
    with check (picked_by_id = auth.uid());
create policy "Authenticated users can update picked products"
    on public.picked_products for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete picked products"
    on public.picked_products for delete to authenticated using (true);

commit;
