begin;

create table public.payment_methods (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    logo_path text,
    bank_account varchar(100),
    merchant_city varchar(100) not null,
    currency varchar(10),
    store_label varchar(255),
    is_cashed boolean not null default true,
    is_active boolean not null default true,
    created_by_user_id uuid
        references auth.users(id)
        on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index payment_methods_active_idx
    on public.payment_methods(is_active, created_at desc);

alter table public.payment_methods enable row level security;

create policy "Public can read payment methods"
    on public.payment_methods for select to public using (true);
create policy "Authenticated users can create payment methods"
    on public.payment_methods for insert to authenticated with check (true);
create policy "Authenticated users can update payment methods"
    on public.payment_methods for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete payment methods"
    on public.payment_methods for delete to authenticated using (true);

commit;
