begin;

create table public.product_images (
    id bigint generated by default as identity primary key,
    product_id uuid not null
        references public.products(id)
        on delete cascade,
    image_path text not null,
    is_active boolean not null default false,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    constraint product_images_path_unique unique (product_id, image_path)
);

create index product_images_product_id_idx
    on public.product_images(product_id);

-- A product can have only one image selected as its thumbnail.
create unique index product_images_one_active_per_product_idx
    on public.product_images(product_id)
    where is_active;

insert into public.product_images (
    product_id,
    image_path,
    is_active,
    sort_order
)
select
    product.id,
    image.path,
    image.position = 1,
    image.position - 1
from public.products as product
cross join lateral unnest(product.thumbnail_paths)
    with ordinality as image(path, position);

alter table public.product_images enable row level security;

create policy "Public can read product images"
    on public.product_images
    for select
    to public
    using (true);

create policy "Authenticated users can create product images"
    on public.product_images
    for insert
    to authenticated
    with check (true);

create policy "Authenticated users can update product images"
    on public.product_images
    for update
    to authenticated
    using (true)
    with check (true);

create policy "Authenticated users can delete product images"
    on public.product_images
    for delete
    to authenticated
    using (true);

alter table public.products
    drop column thumbnail_paths,
    drop column is_active;

commit;
