begin;

create table public.banners (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description text,
    thumbnail_path text not null,
    product_id bigint not null
        references public.products(id)
        on delete restrict,
    is_active boolean not null default true,
    created_by_user_id uuid
        references auth.users(id)
        on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index banners_product_id_idx on public.banners(product_id);
create index banners_active_created_at_idx
    on public.banners(is_active, created_at desc);

alter table public.banners enable row level security;

create policy "Public can read banners"
    on public.banners for select to public using (true);
create policy "Authenticated users can create banners"
    on public.banners for insert to authenticated
    with check (created_by_user_id = auth.uid());
create policy "Authenticated users can update banners"
    on public.banners for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete banners"
    on public.banners for delete to authenticated using (true);

commit;
