create sequence public.category_code_seq start with 1;

create table public.categories (
    id bigint generated by default as identity primary key,

    code varchar(50) not null unique default (
        'CAT' || lpad(nextval('public.category_code_seq')::text, 5, '0')
    ),
    name varchar(255) not null,

    parent_id bigint
        references public.categories(id)
        on delete set null,

    created_by_user_id uuid
        references auth.users(id)
        on delete set null,

    is_active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter sequence public.category_code_seq owned by public.categories.code;
