begin;

create type public.sale_status as enum ('draft', 'completed');

create table public.sales (
    id bigint generated by default as identity primary key,
    code varchar(11) generated always as (
        'SAL'
        || lpad(((extract(year from sale_date)::integer % 100))::text, 2, '0')
        || lpad(id::text, 6, '0')
    ) stored unique,
    sale_date date not null default current_date,
    sale_to uuid not null references auth.users(id) on delete restrict,
    payment_method_id bigint not null
        references public.payment_methods(id) on delete restrict,
    description text,
    status public.sale_status not null default 'draft',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint sales_id_code_range_check check (id between 1 and 999999)
);

create table public.sale_items (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references public.sales(id) on delete cascade,
    product_id uuid not null references public.products(id) on delete restrict,
    quantity integer not null check (quantity > 0),
    unit_price numeric(12, 2) not null check (unit_price >= 0),
    discount numeric(12, 2) not null default 0
        check (discount >= 0 and discount <= unit_price),
    created_at timestamptz not null default now(),
    constraint sale_items_product_unique unique (sale_id, product_id)
);

create index sales_date_idx on public.sales(sale_date desc);
create index sales_payment_method_id_idx on public.sales(payment_method_id);
create index sales_sale_to_idx on public.sales(sale_to);
create index sale_items_sale_id_idx on public.sale_items(sale_id);
create index sale_items_product_id_idx on public.sale_items(product_id);

alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

create policy "Authenticated users can read sales"
    on public.sales for select to authenticated using (true);
create policy "Authenticated users can read sale items"
    on public.sale_items for select to authenticated using (true);

create function public.save_sale(
    p_id bigint,
    p_sale_date date,
    p_payment_method_id bigint,
    p_description text,
    p_status public.sale_status,
    p_items jsonb
)
returns public.sales
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_sale public.sales;
    v_existing public.sales;
    v_item_count integer;
    v_distinct_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;
    if p_sale_date is null then
        raise exception 'Sale date is required';
    end if;
    if p_payment_method_id is null or not exists (
        select 1 from public.payment_methods
        where id = p_payment_method_id and is_active
    ) then
        raise exception 'An active payment method is required';
    end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array'
        or jsonb_array_length(p_items) = 0 then
        raise exception 'At least one sale item is required';
    end if;

    select count(*), count(distinct product_id)
    into v_item_count, v_distinct_count
    from jsonb_to_recordset(p_items)
        as item(product_id uuid, quantity integer);
    if v_item_count <> v_distinct_count then
        raise exception 'A product cannot be selected more than once';
    end if;
    if exists (
        select 1 from jsonb_to_recordset(p_items)
            as item(product_id uuid, quantity integer)
        where product_id is null or quantity is null or quantity <= 0
    ) then
        raise exception 'Every item requires a product and a positive quantity';
    end if;

    if p_id is not null then
        select * into v_existing
        from public.sales where id = p_id for update;
        if not found then
            raise exception 'Sale % was not found', p_id;
        end if;

    end if;

    -- Serialize stock checks and updates for every old/new product so two
    -- completed sales cannot consume the same available units concurrently.
    perform 1
    from public.stocks
    where product_id in (
        select item.product_id
        from jsonb_to_recordset(p_items)
            as item(product_id uuid, quantity integer)
        union
        select line.product_id
        from public.sale_items as line
        where line.sale_id = p_id
    )
    order by product_id
    for update;

    if p_id is not null then
        if v_existing.status = 'completed' then
            update public.stocks as stock
            set stock_out = stock.stock_out - line.quantity,
                updated_at = now()
            from public.sale_items as line
            where line.sale_id = p_id
              and stock.product_id = line.product_id;
        end if;

        delete from public.sale_items where sale_id = p_id;
    end if;

    if p_status = 'completed' and exists (
        select 1
        from jsonb_to_recordset(p_items)
            as item(product_id uuid, quantity integer)
        left join public.stocks as stock on stock.product_id = item.product_id
        where stock.id is null
           or item.quantity > (stock.stock_in + stock.stock_adjustment - stock.stock_out)
    ) then
        raise exception 'One or more products have insufficient stock';
    end if;

    if p_id is null then
        insert into public.sales (
            sale_date, sale_to, payment_method_id, description, status
        ) values (
            p_sale_date, auth.uid(), p_payment_method_id,
            nullif(btrim(p_description), ''), p_status
        ) returning * into v_sale;
    else
        update public.sales
        set sale_date = p_sale_date,
            sale_to = auth.uid(),
            payment_method_id = p_payment_method_id,
            description = nullif(btrim(p_description), ''),
            status = p_status,
            updated_at = now()
        where id = p_id
        returning * into v_sale;
    end if;

    insert into public.sale_items (
        sale_id, product_id, quantity, unit_price, discount
    )
    select
        v_sale.id,
        item.product_id,
        item.quantity,
        product.unit_price,
        product.discount
    from jsonb_to_recordset(p_items)
        as item(product_id uuid, quantity integer)
    join public.products as product on product.id = item.product_id;

    if not found or (select count(*) from public.sale_items where sale_id = v_sale.id) <> v_item_count then
        raise exception 'One or more selected products do not exist';
    end if;

    if p_status = 'completed' then
        update public.stocks as stock
        set stock_out = stock.stock_out + requested.quantity,
            updated_at = now()
        from (
            select product_id, sum(quantity)::integer as quantity
            from public.sale_items
            where sale_id = v_sale.id
            group by product_id
        ) as requested
        where stock.product_id = requested.product_id;
    end if;

    return v_sale;
end;
$$;

create function public.delete_sale(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_status public.sale_status;
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;

    select status into v_status from public.sales where id = p_id for update;
    if not found then
        raise exception 'Sale % was not found', p_id;
    end if;

    if v_status = 'completed' then
        update public.stocks as stock
        set stock_out = stock.stock_out - line.quantity,
            updated_at = now()
        from public.sale_items as line
        where line.sale_id = p_id
          and stock.product_id = line.product_id;
    end if;

    delete from public.sales where id = p_id;
end;
$$;

revoke all on function public.save_sale(bigint, date, bigint, text, public.sale_status, jsonb) from public;
revoke all on function public.delete_sale(bigint) from public;
grant execute on function public.save_sale(bigint, date, bigint, text, public.sale_status, jsonb) to authenticated;
grant execute on function public.delete_sale(bigint) to authenticated;

commit;
