begin;

create table public.stock_adjustments (
    id bigint generated by default as identity primary key,
    code varchar(11) generated always as (
        'SADI'
        || lpad(((extract(year from stock_adjustment_date)::integer % 100))::text, 2, '0')
        || lpad(id::text, 5, '0')
    ) stored unique,
    stock_adjustment_date date not null default current_date,
    description text,
    created_by_user_id uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint stock_adjustments_id_code_range_check check (id between 1 and 99999)
);

create table public.stock_adjustment_items (
    id bigint generated by default as identity primary key,
    stock_adjustment_id bigint not null
        references public.stock_adjustments(id) on delete cascade,
    product_id uuid not null
        references public.products(id) on delete restrict,
    quantity integer not null check (quantity <> 0),
    note text,
    created_at timestamptz not null default now(),
    constraint stock_adjustment_items_product_unique
        unique (stock_adjustment_id, product_id)
);

create index stock_adjustments_date_idx
    on public.stock_adjustments(stock_adjustment_date desc);
create index stock_adjustment_items_adjustment_id_idx
    on public.stock_adjustment_items(stock_adjustment_id);
create index stock_adjustment_items_product_id_idx
    on public.stock_adjustment_items(product_id);

alter table public.stock_adjustments enable row level security;
alter table public.stock_adjustment_items enable row level security;

create policy "Public can read stock adjustments"
    on public.stock_adjustments for select to public using (true);
create policy "Authenticated users can create stock adjustments"
    on public.stock_adjustments for insert to authenticated
    with check (created_by_user_id = auth.uid());
create policy "Authenticated users can update stock adjustments"
    on public.stock_adjustments for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete stock adjustments"
    on public.stock_adjustments for delete to authenticated using (true);

create policy "Public can read stock adjustment items"
    on public.stock_adjustment_items for select to public using (true);
create policy "Authenticated users can create stock adjustment items"
    on public.stock_adjustment_items for insert to authenticated with check (true);
create policy "Authenticated users can update stock adjustment items"
    on public.stock_adjustment_items for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete stock adjustment items"
    on public.stock_adjustment_items for delete to authenticated using (true);

create function public.apply_stock_adjustment_item_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if tg_op = 'INSERT' then
        update public.stocks
        set stock_adjustment = stock_adjustment + new.quantity,
            updated_at = now()
        where product_id = new.product_id;
        if not found then
            raise exception 'Stock record does not exist for product %', new.product_id;
        end if;
        return new;
    elsif tg_op = 'UPDATE' then
        if old.product_id = new.product_id then
            update public.stocks
            set stock_adjustment = stock_adjustment + new.quantity - old.quantity,
                updated_at = now()
            where product_id = new.product_id;
        else
            update public.stocks
            set stock_adjustment = stock_adjustment - old.quantity,
                updated_at = now()
            where product_id = old.product_id;
            update public.stocks
            set stock_adjustment = stock_adjustment + new.quantity,
                updated_at = now()
            where product_id = new.product_id;
        end if;
        return new;
    else
        update public.stocks
        set stock_adjustment = stock_adjustment - old.quantity,
            updated_at = now()
        where product_id = old.product_id;
        return old;
    end if;
end;
$$;

create trigger apply_stock_adjustment_item_change_trigger
after insert or update or delete on public.stock_adjustment_items
for each row execute function public.apply_stock_adjustment_item_change();

create function public.save_stock_adjustment(
    p_id bigint,
    p_stock_adjustment_date date,
    p_description text,
    p_items jsonb
)
returns public.stock_adjustments
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_adjustment public.stock_adjustments;
    v_item_count integer;
    v_distinct_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;
    if p_stock_adjustment_date is null then
        raise exception 'Stock-adjustment date is required';
    end if;
    if p_items is null or jsonb_typeof(p_items) <> 'array'
        or jsonb_array_length(p_items) = 0 then
        raise exception 'At least one adjustment item is required';
    end if;

    select count(*), count(distinct product_id)
    into v_item_count, v_distinct_count
    from jsonb_to_recordset(p_items)
        as item(product_id uuid, quantity integer, note text);
    if v_item_count <> v_distinct_count then
        raise exception 'A product cannot be selected more than once';
    end if;
    if exists (
        select 1 from jsonb_to_recordset(p_items)
            as item(product_id uuid, quantity integer, note text)
        where product_id is null or quantity is null or quantity = 0
    ) then
        raise exception 'Every item requires a product and a non-zero quantity';
    end if;

    if p_id is null then
        insert into public.stock_adjustments (
            stock_adjustment_date, description, created_by_user_id
        ) values (
            p_stock_adjustment_date, nullif(btrim(p_description), ''), auth.uid()
        ) returning * into v_adjustment;
    else
        update public.stock_adjustments
        set stock_adjustment_date = p_stock_adjustment_date,
            description = nullif(btrim(p_description), ''),
            updated_at = now()
        where id = p_id
        returning * into v_adjustment;
        if not found then
            raise exception 'Stock-adjustment record % was not found', p_id;
        end if;
        delete from public.stock_adjustment_items where stock_adjustment_id = p_id;
    end if;

    insert into public.stock_adjustment_items (
        stock_adjustment_id, product_id, quantity, note
    )
    select
        v_adjustment.id,
        item.product_id,
        item.quantity,
        nullif(btrim(item.note), '')
    from jsonb_to_recordset(p_items)
        as item(product_id uuid, quantity integer, note text);

    return v_adjustment;
end;
$$;

create function public.delete_stock_adjustment(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;
    delete from public.stock_adjustments where id = p_id;
    if not found then
        raise exception 'Stock-adjustment record % was not found', p_id;
    end if;
end;
$$;

revoke all on function public.save_stock_adjustment(bigint, date, text, jsonb) from public;
revoke all on function public.delete_stock_adjustment(bigint) from public;
grant execute on function public.save_stock_adjustment(bigint, date, text, jsonb)
    to authenticated;
grant execute on function public.delete_stock_adjustment(bigint) to authenticated;

commit;
