begin;

create table public.user_profiles (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique references auth.users(id) on delete cascade,
    full_name varchar(255) not null default '',
    role varchar(50) not null default 'customer'
        check (role in ('customer', 'admin')),
    profile text default null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index user_profiles_role_idx on public.user_profiles(role);
create index user_profiles_full_name_idx on public.user_profiles(full_name);

insert into public.user_profiles (user_id, full_name, role, profile, created_at, updated_at)
select
    user_record.id,
    coalesce(user_record.raw_user_meta_data ->> 'full_name', ''),
    case
        when lower(coalesce(
            user_record.raw_app_meta_data ->> 'role',
            user_record.raw_user_meta_data ->> 'role',
            'customer'
        )) = 'admin' then 'admin'
        else 'customer'
    end,
    nullif(user_record.raw_user_meta_data ->> 'profile', ''),
    user_record.created_at,
    coalesce(user_record.updated_at, user_record.created_at)
from auth.users as user_record
on conflict (user_id) do nothing;

create function public.sync_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.user_profiles (user_id, full_name, role, profile)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        case when lower(coalesce(new.raw_app_meta_data ->> 'role', '')) = 'admin'
            then 'admin' else 'customer' end,
        nullif(new.raw_user_meta_data ->> 'profile', '')
    )
    on conflict (user_id) do update
    set full_name = coalesce(new.raw_user_meta_data ->> 'full_name', public.user_profiles.full_name),
        profile = coalesce(nullif(new.raw_user_meta_data ->> 'profile', ''), public.user_profiles.profile),
        updated_at = now();
    return new;
end;
$$;

create trigger sync_auth_user_profile
after insert or update of raw_user_meta_data on auth.users
for each row execute function public.sync_user_profile();

create function public.is_profile_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1 from public.user_profiles
        where user_id = auth.uid() and role = 'admin'
    );
$$;

alter table public.user_profiles enable row level security;

create policy "Users can read their own profile"
    on public.user_profiles for select to authenticated
    using (user_id = auth.uid());
create policy "Admins can read all profiles"
    on public.user_profiles for select to authenticated
    using (public.is_profile_admin());
create policy "Users can update their own profile"
    on public.user_profiles for update to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

revoke all on public.user_profiles from anon, authenticated;
grant select on public.user_profiles to authenticated;
grant update (full_name, profile, updated_at) on public.user_profiles to authenticated;

create function public.admin_update_user_profile(
    p_user_id uuid,
    p_full_name text,
    p_role text,
    p_profile text
)
returns public.user_profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
    updated_profile public.user_profiles;
begin
    if not public.is_profile_admin() then
        raise exception 'Administrator access is required';
    end if;
    if p_role not in ('customer', 'admin') then
        raise exception 'Invalid user role';
    end if;
    if nullif(btrim(p_full_name), '') is null then
        raise exception 'Full name is required';
    end if;

    update public.user_profiles
    set full_name = btrim(p_full_name),
        role = p_role,
        profile = nullif(btrim(p_profile), ''),
        updated_at = now()
    where user_id = p_user_id
    returning * into updated_profile;

    if not found then raise exception 'User profile was not found'; end if;

    update auth.users
    set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
        || jsonb_build_object('full_name', updated_profile.full_name, 'profile', updated_profile.profile),
        raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
        || jsonb_build_object('role', updated_profile.role),
        updated_at = now()
    where id = p_user_id;

    return updated_profile;
end;
$$;

revoke all on function public.is_profile_admin() from public;
revoke all on function public.admin_update_user_profile(uuid, text, text, text) from public;
grant execute on function public.is_profile_admin() to authenticated;
grant execute on function public.admin_update_user_profile(uuid, text, text, text) to authenticated;

commit;
