begin;

create table public.stock_ins (
    id bigint generated by default as identity primary key,
    code varchar(10) generated always as (
        'STI'
        || lpad(((extract(year from stock_in_date)::integer % 100))::text, 2, '0')
        || lpad(id::text, 5, '0')
    ) stored unique,
    stock_in_date date not null default current_date,
    description text,
    created_by_user_id uuid
        references auth.users(id)
        on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint stock_ins_id_code_range_check check (id between 1 and 99999)
);

create table public.stock_in_items (
    id bigint generated by default as identity primary key,
    stock_in_id bigint not null
        references public.stock_ins(id)
        on delete cascade,
    product_id bigint not null
        references public.products(id)
        on delete restrict,
    quantity integer not null check (quantity > 0),
    note text,
    created_at timestamptz not null default now(),
    constraint stock_in_items_product_unique unique (stock_in_id, product_id)
);

create index stock_ins_date_idx on public.stock_ins(stock_in_date desc);
create index stock_in_items_stock_in_id_idx on public.stock_in_items(stock_in_id);
create index stock_in_items_product_id_idx on public.stock_in_items(product_id);

alter table public.stock_ins enable row level security;
alter table public.stock_in_items enable row level security;

create policy "Public can read stock ins"
    on public.stock_ins for select to public using (true);
create policy "Authenticated users can create stock ins"
    on public.stock_ins for insert to authenticated
    with check (created_by_user_id = auth.uid());
create policy "Authenticated users can update stock ins"
    on public.stock_ins for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete stock ins"
    on public.stock_ins for delete to authenticated using (true);

create policy "Public can read stock in items"
    on public.stock_in_items for select to public using (true);
create policy "Authenticated users can create stock in items"
    on public.stock_in_items for insert to authenticated with check (true);
create policy "Authenticated users can update stock in items"
    on public.stock_in_items for update to authenticated
    using (true) with check (true);
create policy "Authenticated users can delete stock in items"
    on public.stock_in_items for delete to authenticated using (true);

create function public.apply_stock_in_item_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if tg_op = 'INSERT' then
        update public.stocks
        set stock_in = stock_in + new.quantity,
            updated_at = now()
        where product_id = new.product_id;

        if not found then
            raise exception 'Stock record does not exist for product %', new.product_id;
        end if;
        return new;
    elsif tg_op = 'UPDATE' then
        if old.product_id = new.product_id then
            update public.stocks
            set stock_in = stock_in + new.quantity - old.quantity,
                updated_at = now()
            where product_id = new.product_id;
        else
            update public.stocks
            set stock_in = stock_in - old.quantity,
                updated_at = now()
            where product_id = old.product_id;

            update public.stocks
            set stock_in = stock_in + new.quantity,
                updated_at = now()
            where product_id = new.product_id;
        end if;
        return new;
    else
        update public.stocks
        set stock_in = stock_in - old.quantity,
            updated_at = now()
        where product_id = old.product_id;
        return old;
    end if;
end;
$$;

create trigger apply_stock_in_item_change_trigger
after insert or update or delete on public.stock_in_items
for each row execute function public.apply_stock_in_item_change();

create function public.save_stock_in(
    p_id bigint,
    p_stock_in_date date,
    p_description text,
    p_items jsonb
)
returns public.stock_ins
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_stock_in public.stock_ins;
    v_item_count integer;
    v_distinct_count integer;
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;

    if p_stock_in_date is null then
        raise exception 'Stock-in date is required';
    end if;

    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception 'At least one stock-in item is required';
    end if;

    select count(*), count(distinct product_id)
    into v_item_count, v_distinct_count
    from jsonb_to_recordset(p_items) as item(product_id bigint, quantity integer, note text);

    if v_item_count <> v_distinct_count then
        raise exception 'A product cannot be selected more than once';
    end if;

    if exists (
        select 1
        from jsonb_to_recordset(p_items) as item(product_id bigint, quantity integer, note text)
        where product_id is null or quantity is null or quantity <= 0
    ) then
        raise exception 'Every item requires a product and a positive quantity';
    end if;

    if p_id is null then
        insert into public.stock_ins (stock_in_date, description, created_by_user_id)
        values (p_stock_in_date, nullif(btrim(p_description), ''), auth.uid())
        returning * into v_stock_in;
    else
        update public.stock_ins
        set stock_in_date = p_stock_in_date,
            description = nullif(btrim(p_description), ''),
            updated_at = now()
        where id = p_id
        returning * into v_stock_in;

        if not found then
            raise exception 'Stock-in record % was not found', p_id;
        end if;

        delete from public.stock_in_items where stock_in_id = p_id;
    end if;

    insert into public.stock_in_items (stock_in_id, product_id, quantity, note)
    select
        v_stock_in.id,
        item.product_id,
        item.quantity,
        nullif(btrim(item.note), '')
    from jsonb_to_recordset(p_items) as item(product_id bigint, quantity integer, note text);

    return v_stock_in;
end;
$$;

create function public.delete_stock_in(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception 'Authentication required';
    end if;

    delete from public.stock_ins where id = p_id;
    if not found then
        raise exception 'Stock-in record % was not found', p_id;
    end if;
end;
$$;

revoke all on function public.save_stock_in(bigint, date, text, jsonb) from public;
revoke all on function public.delete_stock_in(bigint) from public;
grant execute on function public.save_stock_in(bigint, date, text, jsonb) to authenticated;
grant execute on function public.delete_stock_in(bigint) to authenticated;

commit;
